<template>
  <div class="flex flex-col justify-center md:gap-y-[4rem] gap-y-4 h-[38rem]">
    <h2 class="text-[#202326] md:text-[2.5rem] text-[1.375rem] font-[800] mb-[0.75rem]">Verify Authenticator</h2>
    
    <div v-if="apiError" class="mb-[1.25rem] text-[0.875rem] text-red-500">
      {{ apiError }}
    </div>

    <form @submit.prevent="$emit('submit', form)">
      <!-- 验证码输入 -->
      <label class="md:text-[1.25rem] text-md font-[600]">Authenticator App Code</label><br>
      <div class="mt-[0.5rem]"></div>
      <input 
        required 
        v-model="form.otpCode" 
        type="text" 
        inputmode="numeric"
        pattern="[0-9]*"
        maxlength="6"
        @input="$emit('clear-error', 'otpCode')"
        class="wuBuTip md:w-[33.0rem] w-full border rounded-2xl py-[0.75rem] px-[1.5rem] text-[1.25rem] block text-center tracking-[0.5rem]"
        placeholder="••••••"
      >
      <div v-if="errors.otpCode" class="mb-[1.25rem] text-[0.625rem] text-red-400">
        {{ errors.otpCode }}
      </div>

      <div class="flex items-center mt-[1.5rem]">
        <label class="text-[1.0rem] text-[#8D8D8D]">
          <!-- enter the 6-digit otpCode generated by the authenticator app. -->
          enter the 6-digit otpCode sent to your email.
        </label>
      </div>

      <!-- 验证按钮 -->
      <button 
        type="submit"
        class="text-[1.5rem] font-[700] text-white bg-[#FF7545] md:w-[33.4375rem] w-full h-[3.75rem] rounded-[2.5rem] mt-[1.875rem]"
      >
        Verify
      </button>
    </form>

  </div>
</template>

<script setup>
defineProps({
  form: {
    type: Object,
    required: true,
    default: () => ({
      otpCode: '',
    })
  },
  errors: {
    type: Object,
    required: true,
    default: () => ({})
  },
  apiError: {
    type: String,
    default: ''
  }
});

defineEmits(['submit', 'clear-error']);
</script>